### ISSUE TITLE
Some data file cannot be imported but withou any error message

### ISSUE THREAD

**Issue by medpower** [savian-net/SaviTransport#1]
Dear AlanC,

Here is an issue that when import some XPT files, there is nothing returned. However, if drop some variable, then it works. I just attached some sample data for the test purpose with the link below. 
[Sample Data](https://data42.cn/tmp/testdata.zip)

There are two sets of sample data (dm1 vs dm2 and pr1 and pr2), the difference betteen each set was just additional one variable kept or dropped. However, only one of them could be imported successfully. I haven't figured out the reason behind the issue. Could you please help to have a try and test if either of these datasets could be imported successfully from your side?

Thanks a lot!

Regards,
Stanley

**Comment by savian-net** [comment]
Fixed in latest. Issue is how to calculate end of variable header record. You have to gobble bytes if less than 80 left unless it is zero. Added logic to handle. Also cleared 2 null refs.
